# Generated by Django 4.2.7 on 2023-12-09 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("deliver", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.CreateModel(
            name="PostAvailability",
            fields=[
                ("postid", models.AutoField(primary_key=True, serialize=False)),
                ("starttime", models.CharField(max_length=25)),
                ("endtime", models.CharField(max_length=25)),
                ("availroute", models.CharField(max_length=100)),
                (
                    "partner_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deliver.partner",
                    ),
                ),
            ],
        ),
    ]
