# Generated by Django 4.2.7 on 2023-12-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deliver", "0002_partner_status_postavailability"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postavailability",
            old_name="availroute",
            new_name="startlocation",
        ),
        migrations.AddField(
            model_name="postavailability",
            name="endlocation",
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
