# Generated by Django 4.2.7 on 2023-12-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0003_rename_availroute_postavailability_startlocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postavailability',
            name='endlatitude',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postavailability',
            name='endlongitude',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postavailability',
            name='startlatitude',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postavailability',
            name='startlongitude',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
