# Generated by Django 4.2.7 on 2023-12-13 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0004_postavailability_endlatitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('requestid', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=100)),
                ('package_type', models.CharField(max_length=70)),
                ('package_size', models.CharField(max_length=5)),
                ('pickup_point', models.CharField(max_length=100)),
                ('drop_point', models.CharField(max_length=100)),
                ('pickup_latitude', models.CharField(max_length=200)),
                ('pickup_longitude', models.CharField(max_length=200)),
                ('drop_latitude', models.CharField(max_length=200)),
                ('drop_longitude', models.CharField(max_length=200)),
                ('deliveryinfo', models.CharField(max_length=200)),
                ('status', models.CharField(default='requested', max_length=25)),
                ('courier_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deliver.partner')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliver.customer')),
            ],
        ),
    ]
