# Generated by Django 4.2.7 on 2023-12-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0005_deliveryrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryRequest',
        ),
    ]
