# Generated by Django 4.2.7 on 2023-12-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deliver", "0007_deliveryrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryrequest",
            name="amount",
            field=models.CharField(default=2, max_length=5),
            preserve_default=False,
        ),
    ]
