# Generated by Django 4.2.7 on 2023-12-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deliver", "0009_partner_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryrequest",
            name="status",
            field=models.CharField(default="requested", max_length=50),
        ),
    ]
