# Generated by Django 4.2.7 on 2023-12-16 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("deliver", "0010_alter_deliveryrequest_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payments",
            fields=[
                ("payment_id", models.AutoField(primary_key=True, serialize=False)),
                ("payment_status", models.CharField(max_length=10)),
                (
                    "courier_partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deliver.partner",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deliver.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedbacks",
            fields=[
                ("feedback_id", models.AutoField(primary_key=True, serialize=False)),
                ("feedback", models.CharField(max_length=200)),
                (
                    "courier_partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deliver.partner",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deliver.customer",
                    ),
                ),
            ],
        ),
    ]
