# Generated by Django 4.2.7 on 2023-12-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deliver", "0011_payments_feedbacks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payments",
            name="courier_partner",
        ),
        migrations.RemoveField(
            model_name="payments",
            name="customer",
        ),
        migrations.AddField(
            model_name="deliveryrequest",
            name="feedback",
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deliveryrequest",
            name="payment_status",
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deliveryrequest",
            name="rate",
            field=models.CharField(default=3, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Feedbacks",
        ),
        migrations.DeleteModel(
            name="Payments",
        ),
    ]
